"""Emit a self-contained Python parser from a built parse table.

``generate_parser`` writes a standalone module (``theparser.py``) that embeds the
ACTION/GOTO tables and a compact LR driver.  The file has **no dependency on
yapargen** — it can be shipped next to a YALex-generated lexer and run on its
own.  It exposes:

* ``parse(tokens) -> ParseResult`` — drive a parse over terminal names / tokens;
* a ``__main__`` block that reads whitespace-separated terminal names from a
  file (or stdin) and prints the trace plus accept/reject.

The data tables are injected with ``ascii()`` (pure-ASCII source) and the parser
runtime is a fixed code block, so no fragile string templating is involved.
"""

from __future__ import annotations

from pathlib import Path
from typing import Union

from .grammar import END_MARKER
from .lalr_table import LALRTable
from .slr_table import SLRTable

AnyTable = Union[SLRTable, LALRTable]


def generate_parser(table: AnyTable, output_path: str | Path) -> Path:
    """Generate a standalone parser module for *table* at *output_path*."""
    grammar = table.grammar
    prod_index = grammar.production_index()

    productions = [(p.head, list(p.body), str(p)) for p in grammar.productions]

    action: dict[tuple[int, str], tuple[str, object]] = {}
    for (state, term), act in table.action.items():
        kind, value = act
        if kind == "reduce":
            action[(state, term)] = ("reduce", prod_index[value])
        else:
            action[(state, term)] = (kind, value)

    data_block = "\n".join([
        "# -*- coding: utf-8 -*-",
        f"# Auto-generated by yapargen.codegen - {table.kind}(1) parser.",
        "# Standalone: depends only on the Python standard library.",
        "from __future__ import annotations",
        "",
        "import sys",
        "from dataclasses import dataclass, field",
        "from typing import Any, List, Optional",
        "",
        f"PARSER_KIND = {table.kind!r}",
        f"START = {ascii(grammar.start)}",
        f"END_MARKER = {ascii(END_MARKER)}",
        "# (head, body, pretty) per production; index 0 is the augmented start (accept).",
        f"PRODUCTIONS = {ascii(productions)}",
        "# (state, terminal) -> (kind, value);  reduce value is a production index.",
        f"ACTION = {ascii(action)}",
        f"GOTO = {ascii(dict(table.goto))}",
        f"TERMINALS = {ascii(sorted(grammar.terminals))}",
        f"NON_TERMINALS = {ascii(sorted(grammar.non_terminals))}",
        f"CONFLICTS = {ascii(list(table.conflicts))}",
        "",
        "",
    ])

    out = Path(output_path)
    out.parent.mkdir(parents=True, exist_ok=True)
    out.write_text(data_block + _RUNTIME, encoding="utf-8")
    return out


# Fixed runtime appended verbatim after the data block (no templating).
_RUNTIME = r'''
@dataclass
class ParseStep:
    stack: str
    input: str
    action: str


@dataclass
class ParseResult:
    accepted: bool
    steps: List[ParseStep] = field(default_factory=list)
    error: Optional[str] = None

    def __bool__(self) -> bool:
        return self.accepted


def _terminal_of(tok: Any) -> str:
    return tok if isinstance(tok, str) else getattr(tok, "type", str(tok))


def parse(tokens: List[Any]) -> ParseResult:
    """Drive an LR parse over *tokens* (terminal names or objects with .type)."""
    terms = [_terminal_of(t) for t in tokens] + [END_MARKER]
    originals = list(tokens) + [END_MARKER]
    state_stack = [0]
    symbol_stack: List[str] = []
    steps: List[ParseStep] = []
    ip = 0

    def stack_repr() -> str:
        out = str(state_stack[0])
        for sym, st in zip(symbol_stack, state_stack[1:]):
            out += " " + str(sym) + " " + str(st)
        return out

    while True:
        state = state_stack[-1]
        a = terms[ip]
        act = ACTION.get((state, a))
        if act is None:
            expected = sorted(sym for (st, sym) in ACTION if st == state)
            tok = originals[ip]
            pos = ""
            line, col = getattr(tok, "line", None), getattr(tok, "column", None)
            if line is not None and col is not None:
                pos = " en linea " + str(line) + ", columna " + str(col)
            msg = ("Error sintactico: token inesperado '" + str(a) + "'" + pos +
                   ". Se esperaba: " + (", ".join(expected) or "(nada)") + ".")
            steps.append(ParseStep(stack_repr(), " ".join(terms[ip:]), "ERROR"))
            return ParseResult(False, steps, error=msg)
        kind, value = act
        if kind == "shift":
            steps.append(ParseStep(stack_repr(), " ".join(terms[ip:]), "shift -> I" + str(value)))
            symbol_stack.append(a)
            state_stack.append(value)
            ip += 1
        elif kind == "reduce":
            head, body, pretty = PRODUCTIONS[value]
            steps.append(ParseStep(stack_repr(), " ".join(terms[ip:]), "reduce r" + str(value) + ": " + pretty))
            for _ in range(len(body)):
                symbol_stack.pop()
                state_stack.pop()
            t = state_stack[-1]
            goto_state = GOTO.get((t, head))
            if goto_state is None:
                return ParseResult(False, steps, error="Error interno: GOTO ausente")
            symbol_stack.append(head)
            state_stack.append(goto_state)
        elif kind == "accept":
            steps.append(ParseStep(stack_repr(), " ".join(terms[ip:]), "accept"))
            return ParseResult(True, steps)
        else:
            return ParseResult(False, steps, error="accion desconocida")


def format_trace(result: ParseResult) -> str:
    rows = [("Stack", "Input", "Accion")] + [(s.stack, s.input, s.action) for s in result.steps]
    w0 = max(len(r[0]) for r in rows)
    w1 = max(len(r[1]) for r in rows)
    lines = [rows[0][0].ljust(w0) + "  |  " + rows[0][1].ljust(w1) + "  |  " + rows[0][2]]
    lines.append("-" * (w0 + w1 + 14))
    for st, inp, act in rows[1:]:
        lines.append(st.ljust(w0) + "  |  " + inp.ljust(w1) + "  |  " + act)
    lines.append("")
    lines.append("CADENA ACEPTADA" if result.accepted else "CADENA RECHAZADA")
    if result.error:
        lines.append(result.error)
    return "\n".join(lines)


def main(argv: Optional[List[str]] = None) -> int:
    argv = sys.argv[1:] if argv is None else argv
    if CONFLICTS:
        print("AVISO: la tabla tiene " + str(len(CONFLICTS)) + " conflicto(s); el parser puede no ser fiable.")
    if argv:
        text = open(argv[0], encoding="utf-8").read()
    else:
        text = sys.stdin.read()
    tokens = text.split()
    result = parse(tokens)
    print(format_trace(result))
    return 0 if result.accepted else 1


if __name__ == "__main__":
    raise SystemExit(main())
'''
